apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: registry.digitalocean.com/deneme-repo/deneme1:latest
          imagePullPolicy: Always
          env:
            - name: DOCKER_REGISTRY_USERNAME
              valueFrom:
                secretKeyRef:
                  name: digitalocean-registry-secret
                  key: DOCKER_REGISTRY_USERNAME
            - name: DOCKER_REGISTRY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: digitalocean-registry-secret
                  key: DOCKER_REGISTRY_PASSWORD
          ports:
            - protocol: TCP
              containerPort: 80

              


              
