apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: mhart/alpine-node:6.10
          ports:
            - protocol: TCP
              port: 80
              targetPort: 3000
          type: LoadBalancer
