name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DO_TOKEN }}
        
    - name: Set up kubectl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DO_TOKEN }}

    - name: Deploy to Kubernetes
      run: |
        doctl kubernetes cluster kubeconfig save a0a93fca-a609-44f6-939b-a540461d0d6c
        kubectl config get-contexts
        kubectl apply -f ./service.yaml
        kubectl apply -f ./deployment.yaml
        kubectl get services
        kubectl get deployments
        kubectl get service nodejs-app-service -o yaml
        kubectl get LoadBalancer nodejs-app-service -o yaml
        
